### ISSUE TITLE
Latest RHEL9 driver reports: Failed to initialize NVML: Driver/library version mismatch

### ISSUE THREAD

**Issue by ElCoyote27** [negativo17/nvidia-driver#180]
Getting this on all my 9.6 systems:

```
# nvidia-smi 
Failed to initialize NVML: Driver/library version mismatch
NVML library version: 575.64

# rpm -qa|grep nvidia|grep -v pcp
nvidia-xconfig-575.64-1.el9.x86_64
kmod-nvidia-5.14.0-427.el9_4-575.64-1.el9.x86_64
kmod-nvidia-5.14.0-570.el9_6-575.64-1.el9.x86_64
libnvidia-ml-575.64.03-1.el9.x86_64
libnvidia-gpucomp-575.64.03-1.el9.x86_64
libnvidia-cfg-575.64.03-1.el9.x86_64
nvidia-driver-cuda-libs-575.64.03-1.el9.x86_64
nvidia-driver-libs-575.64.03-1.el9.x86_64
nvidia-persistenced-575.64.03-1.el9.x86_64
nvidia-modprobe-575.64.03-1.el9.x86_64
nvidia-kmod-common-575.64.03-1.el9.noarch
akmod-nvidia-575.64.03-1.el9.x86_64
nvidia-driver-575.64.03-1.el9.x86_64
nvidia-libXNVCtrl-575.64.03-1.el9.x86_64
nvidia-libXNVCtrl-devel-575.64.03-1.el9.x86_64
xorg-x11-nvidia-575.64.03-1.el9.x86_64
nvidia-driver-cuda-575.64.03-1.el9.x86_64
libnvidia-fbc-575.64.03-1.el9.x86_64
libnvidia-gpucomp-575.64.03-1.el9.i686
nvidia-driver-cuda-libs-575.64.03-1.el9.i686
libnvidia-ml-575.64.03-1.el9.i686
nvidia-driver-libs-575.64.03-1.el9.i686
libnvidia-fbc-575.64.03-1.el9.i686
kmod-nvidia-5.14.0-570.el9_6-575.64.03-1.el9.x86_64

# modinfo nvidia -F version
575.64


```

**Comment by scaronni** [comment]
The repo is missing `nvidia-xconfig` at version 575.64.03.

I'll fix it immediately, thanks for reporting.

I see that you installed all packages that are driver related. Please note that these package is not installed by default:
{code}
nvidia-xconfig
nvidia-libXNVCtrl-devel
{code}

And you can remove them, so then also your issue is fixed.

Also, I hardly doubt that `nvidia-xconfig` is useful anymore. Please remove it from your systems. If you are using X, maybe you find `nvidia-settings` a bit useful, but that's not on the list above.

**Comment by ElCoyote27** [comment]
Hi @scaronni I updated that rpm but it did not resolve the issue.
Let me dig a litle deeper...
```
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                             1/1 
  Upgrading        : nvidia-xconfig-3:575.64.03-1.el9.x86_64                                                                                     1/2 
  Cleanup          : nvidia-xconfig-3:575.64-1.el9.x86_64                                                                                        2/2 
  Running scriptlet: nvidia-xconfig-3:575.64-1.el9.x86_64                                                                                        2/2 
  Verifying        : nvidia-xconfig-3:575.64.03-1.el9.x86_64                                                                                     1/2 
  Verifying        : nvidia-xconfig-3:575.64-1.el9.x86_64                                                                                        2/2 
Installed products updated.

Upgraded:
  nvidia-xconfig-3:575.64.03-1.el9.x86_64                                                                                                            

Complete!

# nvidia-smi 
Failed to initialize NVML: Driver/library version mismatch
NVML library version: 575.64

```

**Comment by ElCoyote27** [comment]
I no longer see any cuda-\* rpms in https://negativo17.org/repos/nvidia/epel-9/x86_64, they are still present in https://negativo17.org/repos/multimedia/epel-9/x86_64/, though..

**Comment by ElCoyote27** [comment]
I removed the cuda\* rpms, rebooted and it resolved the issue.

**Comment by scaronni** [comment]
Yes, they are momentarily been moved until NVIDIA releases the rhel 10 repos, so AlmaLinux will no longer use my repository.

Glad you solved it, but cuda packages have nothing to do with this. Judging from your comment and the output above, you are using akmod, and you updated the packages without rebooting, and as you can see some modules had an older version.
